import 'package:dio/dio.dart';
import 'package:get/get_core/src/get_main.dart';
import 'package:get/get_instance/src/extension_instance.dart';
import 'package:pro_23/constant/api_constant.dart';
import 'package:pro_23/model/user/user_data_model.dart';
import '../core/util/api_client.dart';
import '../core/util/api_exception.dart';
import '../service/storage_service.dart';

class UserRepository {
  UserRepository(this._api);

  final Dio dio = Dio();
  final ApiClient _api;
  final StorageService storage = Get.find<StorageService>();

  Future<(userData?, String?)> getCurrentUser() async {
    try {
      final response = await _api.get(ApiConstant.currentUser);
      final dynamic dataJson = response['data'];
      if (dataJson != null) {
        return (userData.fromJson(dataJson), null);
      }
      return (null, 'No user data found');
    } on ApiException catch (e) {
      return (null, e.message);
    } catch (e) {
      return (null, e.toString());
    }
  }

  Future<(UserDataModel?, String?)> getUserPage({
    int page = 0,
    int size = 10,
    String? username,
    String? nickName,
    bool? enabled,
  }) async {
    try {
      final response = await _api.get(
        ApiConstant.users,
        query: {
          'page': page,
          'size': size,
          'sortBy': 'createdAt',
          'direction': 'desc',
          if (username != null && username.isNotEmpty) 'username': username,
          if (nickName != null && nickName.isNotEmpty) 'nickName': nickName,
          if (enabled != null) 'enabled': enabled,
        },
      );

      return (UserDataModel.fromJson(response), null);
    } on DioException catch (e) {
      print('========== GET USERS ERROR ==========');
      print('TYPE: ${e.type}');
      print('MESSAGE: ${e.message}');
      print('STATUS: ${e.response?.statusCode}');
      print('RESPONSE: ${e.response?.data}');
      print('REQUEST: ${e.requestOptions.uri}');
      print('======================================');

      return (
        null,
        e.response?.data?['message']?.toString() ??
            e.message ??
            'Request failed',
      );
    } catch (e) {
      print('GET USERS ERROR: $e');

      return (null, e.toString());
    }
  }

  Future<(userData?, String?)> createUser({
    required String username,
    String? nickName,
    required String password,
  }) async {
    try {
      final response = await _api.post(
        ApiConstant.users,
        body: {
          'username': username,
          'nickName': nickName,
          'password': password,
        },
      );
      print('========== CREATE USER RESPONSE ==========');
      print('RESPONSE: $response');
      print('==========================================');
      // 2. ApiClient only returns here if status code is 2xx.
      // Extract the 'data' map from the response JSON body.
      final dynamic dataJson = response['data'];

      if (dataJson != null) {
        // 3. Return the parsed userData model
        return (userData.fromJson(dataJson), null);
      }

      return (null, 'Unexpected response format from server');
    } on ApiException catch (e) {
      // Catch the custom exception generated by ApiClient
      print('Create user API error: ${e.message}');
      return (null, e.message);
    } catch (e) {
      // Catch any other unexpected mapping or local errors
      print('Create user unexpected error: $e');
      return (null, e.toString());
    }
  }

  Future<(bool, String?)> uploadUserImage({
    required int userId,
    required String filePath,
  }) async {
    try {
      await _api.upload(ApiConstant.userImage(userId), filePath: filePath);
      return (true, null);

      // return (false, 'Image upload failed: ${response.statusCode}');
    } on DioException catch (e) {
      return (
        false,
        e.response?.data?['message']?.toString() ??
            e.message ??
            'Image upload failed',
      );
    } catch (e) {
      print(e);
      return (false, e.toString());
    }
  }

  Future<(bool, String?)> userEnabled({
    required int userId,
    required bool enabled,
  }) async {
    try {
      await _api.patch(
        ApiConstant.userEnabled(userId),
        query: {'enabled': enabled},
      );
      return (true, null);
    } on DioException catch (e) {
      return (
        false,
        e.response?.data?['message']?.toString() ??
            e.message ??
            'Image upload failed',
      );
    } catch (e) {
      print(e);
      return (false, e.toString());
    }
  }

  Future<(userData?, String?)> updateUser({required int userId, required String username, String? nickName,}) async {
    try {
      final response = await _api.put(
        ApiConstant.userById(userId),
        body: {'username': username, 'nickName': nickName},
      );

      // Get data from response
      final dynamic dataJson = response['data'];

      if (dataJson != null) {
        return (userData.fromJson(dataJson), null);
      }

      return (null, 'Unexpected response format from server');
    } on ApiException catch (e) {
      print('========== UPDATE USER API ERROR ==========');
      print('MESSAGE: ${e.message}');
      print('===========================================');

      return (null, e.message);
    } on DioException catch (e) {
      print('========== UPDATE USER DIO ERROR ==========');
      print('TYPE: ${e.type}');
      print('MESSAGE: ${e.message}');
      print('STATUS: ${e.response?.statusCode}');
      print('RESPONSE: ${e.response?.data}');
      print('REQUEST: ${e.requestOptions.uri}');
      print('============================================');

      return (
        null,
        e.response?.data?['message']?.toString() ??
            e.message ??
            'Update user failed',
      );
    } catch (e) {
      print('========== UPDATE USER ERROR ==========');
      print(e);
      print('=======================================');

      return (null, e.toString());
    }
  }

  Future<(bool, String?)> deleteUser({required int id}) async {
    try {
      await _api.delete(ApiConstant.userById(id));
      return (true, null);
    } on DioException catch (e) {
      print('========== DELETE DIO ERROR ==========');
      print('TYPE: ${e.type}');
      print('MESSAGE: ${e.message}');
      print('STATUS: ${e.response?.statusCode}');
      print('RESPONSE: ${e.response?.data}');
      print('REQUEST: ${e.requestOptions.uri}');
      print('======================================');

      return (
        false,
        e.response?.data?['message']?.toString() ??
            e.message ??
            'Request failed',
      );
    } catch (e) {
      print('========== DELETE ERROR ==========');
      print(e);
      print('==================================');

      return (false, e.toString());
    }
  }
}
